config/routes.rb
Eje4::Application.routes.draw do
  resources :programmers
  root 'programmers#index'

end

app/models/programmer.rb
class Programmer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  before_action :set_programmer, only: [:show, :edit, :update, :destroy]

  # GET /programmers
  # GET /programmers.json
  def index
    @programmers = Programmer.all
  end

  # GET /programmers/1
  # GET /programmers/1.json
  def show
  end

  # GET /programmers/new
  def new
    @programmer = Programmer.new
  end

  # GET /programmers/1/edit
  def edit
  end

  # POST /programmers
  # POST /programmers.json
  def create
    @programmer = Programmer.new(programmer_params)

    respond_to do |format|
      if @programmer.save
        format.html { redirect_to @programmer, notice: 'Programmer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @programmer }
      else
        format.html { render action: 'new' }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programmers/1
  # PATCH/PUT /programmers/1.json
  def update
    respond_to do |format|
      if @programmer.update(programmer_params)
        format.html { redirect_to @programmer, notice: 'Programmer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programmers/1
  # DELETE /programmers/1.json
  def destroy
    @programmer.destroy
    respond_to do |format|
      format.html { redirect_to programmers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programmer
      @programmer = Programmer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programmer_params
      params.require(:programmer).permit(:name, :expertise, :skills)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eje4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/programmers/_form.html.erb
<%= form_for(@programmer) do |f| %>
  <% if @programmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programmer.errors.count, "error") %> prohibited this programmer from being saved:</h2>

      <ul>
      <% @programmer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :expertise %><br>
    <%= f.text_field :expertise %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programmers/edit.html.erb
<h1>Editing programmer</h1>

<%= render 'form' %>

<%= link_to 'Show', @programmer %> |
<%= link_to 'Back', programmers_path %>

app/views/programmers/index.html.erb
<h1>Listing programmers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Expertise</th>
      <th>Skills</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @programmers.each do |programmer| %>
      <tr>
        <td><%= programmer.name %></td>
        <td><%= programmer.expertise %></td>
        <td><%= programmer.skills %></td>
        <td><%= link_to 'Show', programmer %></td>
        <td><%= link_to 'Edit', edit_programmer_path(programmer) %></td>
        <td><%= link_to 'Destroy', programmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programmer', new_programmer_path %>

app/views/programmers/new.html.erb
<h1>New programmer</h1>

<%= render 'form' %>

<%= link_to 'Back', programmers_path %>

app/views/programmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @programmer.name %>
</p>

<p>
  <strong>Expertise:</strong>
  <%= @programmer.expertise %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @programmer.skills %>
</p>

<%= link_to 'Edit', edit_programmer_path(@programmer) %> |
<%= link_to 'Back', programmers_path %>